#!/bin/env python3

#out      = subprocess.DEVNULL if args.quiet else None
VERS      = '0.1.1'
out       = None
AUR       ='https://AUR.archlinux.org/rpc/?v=5&'
NEW_FMT   = '\033[34m:: \033[0;1m{Name} \033[0;31m{Old}\033[0m -> \033[32m{New}\033[0m'
OLD_FMT   = '\033[34m:: \033[0;1m{Name} \033[0m{Old} != {New}'
aur_url   = "https://aur.archlinux.org/"
build_dir = "/home/justin/Documents/Build/"
repo_dir  = "/home/justin/custom-repo/"
repo      = "/home/justin/custom-repo/custom.db.tar.gz"
